name = "Warmabs"
uuid = "1293a30c-8ee5-487f-8299-33928d5cda09"
authors = ["fjebaker <fergusbkr@gmail.com>"]
version = "0.1.2"

[deps]
LibXSPEC_Warmabs_jll = "cad11c8d-934b-5dad-a678-9ee9e5e00166"
LibXSPEC_jll = "50917eeb-3e3c-5f3a-99bd-93e1c30e1561"
SpectralFitting = "f2c56810-742e-4b72-8bf4-27af3bb81a12"
XSPECModels = "e051c099-9e89-4e1f-aad2-39a4611ecf4d"

[compat]
SpectralFitting = ">=0.6"
XSPECModels = "0.1.1"
